<a href="https://colab.research.google.com/github/ssarinbe24-sys/AI_for_Cybersecurity-/blob/main/Malware_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Required Libraries

Explanation:
Import all necessary Python libraries such as Pandas, NumPy, Matplotlib, and Scikit-learn for data processing, visualization, model training, and evaluation.

In [31]:
import pandas as pd

Load the Dataset

Explanation:
Read the phishing dataset into a Pandas DataFrame for analysis and machine learning operations.

In [32]:
test=pd.read_csv("/content/DynamicMalwareMatrix2.csv")

In [33]:
test

,labels,00,0000,0000000,000000000046,00021401,00c04fc295ee,01,0156250,02,...,windowsruntime,winevt,wmiprvse,working,wow6432node,write,writefile,xaml,xls,zip
0,1,11,0,5,0,0,0,1,6,0,...,0.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,0,0,1,0,0,0,0,0,0,...,0.0,0.0,0.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,0,0,0,0,0,0,0,3,0,...,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,52,0,2,0,0,0,2,0,6,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30673,-1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30674,-1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
30675,-1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
30676,-1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30677,-1,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Test-Size

specifies the proportion of the dataset that will be used for testing the model. The remaining data is used for training.

In [34]:
test.size

15369678

Check Dataset Shape

Explanation:
Determine the number of rows and columns present in the dataset.

In [35]:
test.shape

(30678, 501)

Display Dataset Preview

Explanation:
View the first few rows of the dataset to understand its structure and features.

In [36]:
test.head(5)

,labels,00,0000,0000000,000000000046,00021401,00c04fc295ee,01,0156250,02,...,windowsruntime,winevt,wmiprvse,working,wow6432node,write,writefile,xaml,xls,zip
0,1,11,0,5,0,0,0,1,6,0,...,0.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,0,0,1,0,0,0,0,0,0,...,0.0,0.0,0.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,0,0,0,0,0,0,0,3,0,...,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,52,0,2,0,0,0,2,0,6,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
test.tail(4)

,labels,00,0000,0000000,000000000046,00021401,00c04fc295ee,01,0156250,02,...,windowsruntime,winevt,wmiprvse,working,wow6432node,write,writefile,xaml,xls,zip
30674,-1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
30675,-1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
30676,-1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30677,-1,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
test.sample()

,labels,00,0000,0000000,000000000046,00021401,00c04fc295ee,01,0156250,02,...,windowsruntime,winevt,wmiprvse,working,wow6432node,write,writefile,xaml,xls,zip
23180,-1,0,0,0,0,0,0,0,0,50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Dataset Information

Explanation:
Display column names, data types, and non-null values to understand the dataset better.

In [39]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30678 entries, 0 to 30677
Columns: 501 entries, labels to zip
dtypes: float64(367), int64(134)
memory usage: 117.3 MB

Statistical Summary

Explanation:
Generate summary statistics such as mean, minimum, maximum, and standard deviation.

In [40]:
test.describe()

,labels,00,0000,0000000,000000000046,00021401,00c04fc295ee,01,0156250,02,...,windowsruntime,winevt,wmiprvse,working,wow6432node,write,writefile,xaml,xls,zip
count,30678.000000,30678.000000,30678.000000,30678.000000,30678.000000,30678.000000,30678.000000,30678.000000,30678.000000,30678.000000,...,30677.000000,30677.000000,30677.000000,30677.000000,30677.000000,30677.000000,30677.000000,30677.000000,30677.000000,30677.000000
mean,0.137493,2.614186,0.547167,0.141698,0.163798,0.109036,0.129767,0.567345,0.098051,0.886466,...,0.268964,0.129054,0.203442,0.866936,0.229227,1.684813,0.265313,0.164684,0.265900,0.742022
std,0.990519,16.921098,4.261336,0.981443,1.869420,1.646758,1.718043,4.861703,0.703561,6.383250,...,2.090311,2.137289,2.064684,5.727527,2.273499,2.545616,1.982217,1.721081,2.310352,3.831375
min,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1341.000000,100.000000,57.000000,50.000000,50.000000,47.000000,96.000000,11.000000,54.000000,...,50.000000,50.000000,50.000000,50.000000,43.000000,23.000000,50.000000,57.000000,48.000000,56.000000

Check Missing Values

Explanation:
Identify whether any columns contain missing or null values.

In [41]:
test.isnull()

,labels,00,0000,0000000,000000000046,00021401,00c04fc295ee,01,0156250,02,...,windowsruntime,winevt,wmiprvse,working,wow6432node,write,writefile,xaml,xls,zip
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30673,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30674,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30675,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30676,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30677,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True

Check Missing Values

Explanation:
Identify whether any columns contain missing or null values.

In [42]:
test.isnull().sum()

labels          0
00              0
0000            0
0000000         0
000000000046    0
               ..
write           1
writefile       1
xaml            1
xls             1
zip             1
Length: 501, dtype: int64

In [43]:
print(list(test.columns))

['labels', '00', '0000', '0000000', '000000000046', '00021401', '00c04fc295ee', '01', '0156250', '02', '03', '04', '05', '06', '07', '08', '08002b30309d', '09', '096', '0_x64__8wekyb3d8bbwe', '0e5aae11', '0x0', '0x1', '10', '1000', '1004', '101', '1012', '1036', '1069', '11', '1148', '11cf', '11d0', '11d1', '12', '128', '13', '14', '144', '1440', '1496', '15', '16', '17', '17763', '17763_neutral_neutral_cw5n1h2txyewy', '18', '1836', '189871a37d4dc8849f801e42ea1b8d09167cba5fd9d0b2dadafd002ff99e33ee', '19', '192', '1940', '20', '2018', '2019', '2022', '2040', '20d04fe0', '21', '2103', '22', '2269080069', '23', '2372', '24', '25', '26', '2684', '27', '28', '2828', '288', '29', '30', '3020', '30319_32', '3036', '3052', '3064', '307355e4b60e', '3084', '31', '3156', '3168', '319b4a97ea03', '32', '320', '3240', '328', '33', '3364', '34', '3461203602', '35', '36', '37', '3780', '38', '384', '3876', '3884', '39', '3908', '3aea', '40', '4048', '4096304019', '41', '42', '424c', '4284', '43', '44', '440', '444553540000', '45', '46', '467a', '47', '4700', '48', '4804', '4888', '49', '4951', '4b01', '4c5b', '4dbd', '50', '51', '5108', '511', '5180', '52', '53', '536', '54', '5420', '5476', '55', '56', '57', '576', '58', '588', '59', '608', '68', '696', '707907bf', '71eb', '720', '73', '756', '768', '78', '7fe99a87c641', '7zfm', '7zg', '816', '840', '90', '92703aca08af', '9365', '944', '956b', '9fe2c6153fcb104774c237aa7d9592674bc5f936e9b503a0d243cf0088fcd161', 'a175', 'a2d8', 'a475', 'ab00', 'access', 'activatableclasses', 'activatableclassid', 'alert', 'allappsdesktopapplication', 'allfilesystemobjects', 'allocationsize', 'allowed', 'allowedenumeration', 'app', 'appcore', 'appdata', 'appid', 'application', 'applications', 'appmodel', 'apprepository', 'assembly', 'attributes', 'automaticdestinations', 'b029', 'b4bfcc3a', 'backgroundtaskhost', 'backgroundtasks', 'base', 'basebrd', 'batch2', 'buffer', 'bytes', 'c000', 'c1bac967', 'c66de400274e', 'cached', 'calculator', 'capabilities', 'catroot', 'certificates', 'cff', 'changetime', 'chrmstp', 'chrome', 'classes', 'closefile', 'clsid', 'command', 'commandstore', 'common', 'conhost', 'consent', 'contextmenuhandlers', 'contractid', 'control', 'cortana', 'cortana_1', 'cortana_cw5n1h2txyewy', 'cortanaui', 'cpc', 'createfile', 'createfilemapping', 'creationtime', 'cryptographic', 'cryptography', 'csrss', 'ctfmon', 'current', 'currentcontrolset', 'currentversion', 'customlocale', 'customproperties', 'd3162b92', 'dat', 'data', 'db', 'db2c', 'default', 'defaults', 'delete', 'deletepending', 'desired', 'desktop', 'detect', 'directory', 'disallowed', 'disposition', 'dll', 'dllhost', 'drivers', 'dwm', 'easy', 'efb7', 'en', 'encodingtype', 'endoffile', 'enumerate', 'exe', 'execute', 'exefile', 'explorer', 'extendedlocale', 'extensions', 'f8c9', 'fakenet', 'false', 'fast', 'fastio_release_for_section_synchronization', 'file', 'fileattributes', 'fileexts', 'files', 'flags', 'folder', 'folderdescriptions', 'folders', 'generic', 'globalization', 'google', 'gothic', 'granted', 'handletags', 'hkcr', 'hkcu', 'hklm', 'hku', 'ieuser', 'im_1', 'image', 'impliedselectionmodel', 'index', 'information', 'initpropertybag', 'inprocserver32', 'input', 'instance', 'interface', 'interfaces', 'io', 'irp_mj_close', 'is_0', 'kernel', 'keys', 'keysethandletagsinformation', 'keysetinformationclass', 'languageoverlay', 'lastaccesstime', 'lastwritetime', 'launcher', 'launchworkfolderscontrol', 'length', 'list', 'lnk', 'loc_0409', 'local', 'locales', 'localstate', 'locked', 'low', 'malware', 'manager', 'maximum', 'mca', 'mft', 'microsoft', 'mountpoints2', 'ms', 'mspaint', 'mui', 'mycomputer', 'namespace', 'nativeimages_v4', 'net', 'ni', 'nls', 'non', 'normal', 'notepad', 'nt', 'numberoflinks', 'objects', 'offlinefileslaunchsynccenter', 'offset', 'oid', 'oleaut32', 'open', 'opened', 'openresult', 'openwith', 'openwithprogids', 'options', 'overflow', 'overlaypackages', 'package', 'packageid', 'packagerepository', 'packages', 'page_execute', 'page_nocache', 'pagefile', 'pageprotection', 'paging', 'pak', 'parameters', 'pm', 'png', 'point', 'policies', 'policymanager', 'priority', 'private', 'proc_1', 'process', 'procmon64', 'profilelist', 'profiling', 'program', 'programdata', 'propertybag', 'provider', 'publishers', 'puppet', 'query', 'querybasicinformationfile', 'queryopen', 'querysecurityfile', 'querystandardinformationfile', 'radare2', 'radare2d', 'read', 'readers', 'readfile', 'redirectionmap', 'reg_binary', 'reg_dword', 'reg_expand_sz', 'reg_sz', 'regclosekey', 'regcreatekey', 'regenumkey', 'regenumvalue', 'registry', 'regopenkey', 'regquerykey', 'regqueryvalue', 'regsetinfokey', 'removeproperties', 'reparse', 'repository', 'resources', 'roaming', 'root', 'runas', 'runasuser', 'runtimebroker', 'search', 'searchfilterhost', 'searchindexer', 'searchprotocolhost', 'searchui', 'seconds', 'server', 'services', 'session', 'sessioninfo', 'set', 'settings', 'sharemode', 'shell', 'shellex', 'shellfolder', 'sihost', 'size', 'software', 'start', 'staterepository', 'stateseparation', 'storage', 'strong', 'sub', 'subkeys', 'sublime', 'success', 'svchost', 'synchronize', 'synchronous', 'synctype', 'synctypecreatesection', 'synctypeother', 'sys', 'system32', 'systemcertificates', 'systemfileassociations', 'systemroot', 'syswow64', 'taskhostw', 'tcpip', 'terminal', 'text', 'textinput', 'thread', 'time', 'tools', 'ttc', 'ttf', 'type', 'tzres', 'ui', 'unknown', 'updateencryptionsettingswork', 'user', 'userenv', 'users', 'v4', 'value', 'values', 'vboxservice', 'volume', 'wbem', 'windows', 'windowsapps', 'windowscalculator_10', 'windowsruntime', 'winevt', 'wmiprvse', 'working', 'wow6432node', 'write', 'writefile', 'xaml', 'xls', 'zip']

Exploratory Data Analysis (EDA)

Explanation:
Analyze the distribution of phishing and legitimate websites using charts and graphs.

In [44]:
test["labels"].value_counts()

labels
 1    17448
-1    13230
Name: count, dtype: int64

Feature Selection

Explanation:
Separate input features (X) from the target variable (y) used for prediction.

In [45]:
X=test.drop("labels",axis=1)

In [46]:
y=test["labels"]

Split Dataset into Training and Testing Sets

Explanation:
Divide the dataset into training and testing portions to evaluate model performance on unseen data.

In [47]:
X=test.drop('labels',axis=1)
y=test['labels']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [48]:
X_train

,00,0000,0000000,000000000046,00021401,00c04fc295ee,01,0156250,02,03,...,windowsruntime,winevt,wmiprvse,working,wow6432node,write,writefile,xaml,xls,zip
13271,42,0,0,0,0,0,3,0,0,0,...,11.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0
5191,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
22307,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1812,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
9507,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29802,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5390,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0
860,52,0,0,0,0,0,0,0,0,2,...,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15795,10,0,0,0,0,0,1,0,0,0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
23654,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,15.0

In [49]:
y_test

20770   -1
26936   -1
29942   -1
17117    1
1023     1
        ..
12637    1
1864     1
9682     1
12307    1
3429     1
Name: labels, Length: 7670, dtype: int64

Build the Machine Learning Model

Explanation:
Create a Decision Tree Classifier to classify websites as phishing or legitimate.

Train the Model

Explanation:
Train the model using the training dataset so it can learn phishing patterns.

Make Predictions

Explanation:
Use the trained model to predict the class labels for test data.

Calculate Accuracy

Explanation:
Measure how many predictions were correctly classified.

Generate Confusion Matrix

Explanation:
Evaluate model performance by comparing actual and predicted values.

Classification Report

Explanation:
Display Precision, Recall, F1-Score, and Accuracy for detailed evaluation.

Predict a New Website

Explanation:
Test the model with new website feature values to determine whether it is phishing or legitimate.

In [50]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

In [51]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [52]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
print(f"accuracy :{accuracy:.2f}")

accuracy :1.00

In [53]:
X=test[['labels']]
y=test['windowsruntime']

In [54]:
print(test.isnull().sum())

labels          0
00              0
0000            0
0000000         0
000000000046    0
               ..
write           1
writefile       1
xaml            1
xls             1
zip             1
Length: 501, dtype: int64

In [55]:
print(y.isnull().sum())

1

In [57]:
not_nan_mask = y.notna()
X_clean = X[not_nan_mask]
y_clean = y[not_nan_mask]
X_train,X_test,y_train,y_test=train_test_split(X_clean,y_clean,test_size=0.2,random_state=42)

lr=LinearRegression()
lr.fit(X_train,y_train)
lr_pred=lr.predict(X_test)
lr_r2=r2_score(y_test,lr_pred)

In [58]:
dt=DecisionTreeRegressor(random_state=42)
dt.fit(X_train,y_train)
dt_pred=dt.predict(X_test)
dt_r2=r2_score(y_test,dt_pred)

In [59]:
rf=RandomForestRegressor()
rf.fit(X_train,y_train)
rf_pred=rf.predict(X_test)
rf_r2=r2_score(y_test,rf_pred)

In [60]:
svm = SVC(random_state=42)
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)
svm_acc = accuracy_score(y_test, svm_pred)

In [61]:
print("Linear Regression R^2 Score:", round(lr_r2,3))
print("Decision Tree Regression R^2 Score:", round(dt_r2,3))
print("Random Forest Regression R^2 Score:", round(rf_r2,3))
print("Support Vector Regression R^2 Score:",round(svm_acc,3))

Linear Regression R^2 Score: 0.009
Decision Tree Regression R^2 Score: 0.009
Random Forest Regression R^2 Score: 0.009
Support Vector Regression R^2 Score: 0.95